name: Deploy a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar Surge
      run: npm install --global surge

    - name: Desplegar en Surge
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge --project ./ --domain https://tudominio.surge.sh --token $SURGE_TOKEN




